### ISSUE TITLE
Google Drive link of Parameters

### ISSUE THREAD

**Issue by Oguzhanercan** [wcy-cs/IC-FSRDENet#3]
Can you share the parameters with google drive link? Cannot access Baidu

**Comment by Oguzhanercan** [comment]
Is there any progress about google drive links? @wcy-cs

**Comment by wcy-cs** [comment]
Hello, here is google drive link (https://drive.google.com/drive/folders/1qSSJ46ScGv95XSWSuDOFk3B8U5fJU3DN?usp=drive_link)

**Comment by Oguzhanercan** [comment]
> Hello, here is google drive link (https://drive.google.com/drive/folders/1qSSJ46ScGv95XSWSuDOFk3B8U5fJU3DN?usp=drive_link)

Thank you, I was waiting for this.
